# Generated by Django 4.0.6 on 2024-01-28 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('coordinates', models.CharField(max_length=255)),
                ('intensity', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='uploads/')),
                ('img_date', models.DateField()),
                ('img_time', models.TimeField()),
            ],
        ),
    ]
