# Generated by Django 4.0.6 on 2024-01-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyclone_intensity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddata',
            name='intensity',
        ),
    ]
