# Generated by Django 4.0.6 on 2024-01-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyclone_intensity', '0002_remove_uploadeddata_intensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddata',
            name='coordinates',
        ),
    ]
