# Generated by Django 4.0.6 on 2024-03-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyclone_intensity', '0003_remove_uploadeddata_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddata',
            old_name='images',
            new_name='image',
        ),
    ]
